.TH winewrap-so 1 "October 2014" "winewrap 1.1"
.SH NAME
winewrap-so \- generate files useful for creating a wine dll wrapper of a native library
.SH SYNOPSYS
.B "winewrap-so"
.BI "-I " dir
.RI "["options "] " library dllname
.SH DESCRIPTION
This manual page documents
.BR winewrap-so .
.B winewrap-so
generates files useful when creating a wine dll wrapper of a native library. It is part of the winewrap fork of wrappit4wine.
.SH REQUIRED OPTIONS
.IP \fIlibrary\fR
Native library to grab functions from.
.IP "\fB-I \fIdir\fR, \fB--include-dir \fIdir\fR"
Search \fIdir\fR for headers containing prototypes. This option can be specified multiple times.
.SH OPTIONS
.IP \fIdllname\fR
Name of dll to eventually compile into.
.IP "\fB-p \fIprefix\fR, \fB--prefix \fIprefix\fR"
Use \fIprefix\fR as the string to prepend to wrapper functions. The default prefix is "wine_".
.IP "\fB-h\fR, \fB--generate-header\fR"
Generate a header file in addition to the c source file.
.IP "\fB-t\fR, \fB--add-trace\fR"
Add 'WINE_TRACE("\n");' to wrapper functions.
.IP "\fB--suppress-info-prompt\fR"
Do not ask for wrapper information.
.IP "\fB--suppress-progress\fR"
Do not report wrapper file generation progress.
.IP "\fB--author\fR \fIauthor\fR"
Specify \fIauthor\fR of wrapper. Default is output of "whoami".
.IP "\fB--date\fR \fIdate\fR"
Specify \fIdate\fR of wrapper generation. Default is output of "date" at time of script execution.
.IP "\fB--desc\fR \fIdescription\fR"
Specify short \fIdescription\fR of wrapper.
.IP "\fB--copyright\fR \fInotice\fR"
Specify one-line copyright \fInotice\fR.
.IP "\fB--license\fR \fIlicense\fR"
Specify \fIlicense\fR. Default is "LGPL-2.1+".
.IP "\fB--www\fR \fIwebsite\fR"
Specify \fIwebsite\fR. Default is "https://github.com/SwooshyCueb/wrappit4wine"
.IP "\fB-q\fR"
Quiet operation. Implies \fB--suppress-info-prompt\fR and \fB--suppress-progress\fR.
.IP "\fB--help\fR"
Show usage information.
.SH BUGS
.B winewrap-so
currently cannot wrap functions whose declarations are generated by the C preprocessor.
.SH AUTHOR
Markus Kitsinger <root@swooshalicio.us>
.nf
https://github.com/SwooshyCueb/winewrap
.P
wrappit4wine originally by Juraj Puchký - Devtech <sjurajpuchky@seznam.cz>
.nf
https://github.com/sjurajpuchky/wrappit4wine
.SH AVAILABILITY
.B winewrap-so
is part of winewrap
.SH SEE ALSO
winewrap-dll(1), winedump(1)
